#!/bin/sh

DISKS_BASE_URL=http://archive.org/download/IBM_PC_Compatibles_TOSEC_2012_04_23/IBM_PC_Compatibles_TOSEC_2012_04_23.zip
# DR-DOS 7.02
#IMG=IBM%%20PC%%20Compatibles%%20%%5BTOSEC%%5D%%2FIBM%%20PC%%20Compatibles%%20-%%20Operating%%20Systems%%20-%%20%%5BIMA%%5D%%20%%28TOSEC-v2011-01-06_CM%%29%%2FCaldera%%20DR-DOS%%20v7.02%%20%%281998%%29%%28Caldera%%29%%28Disk%%20%d%%20of%%205%%29.zip

# DR-DOS 7.03
IMG=IBM%%20PC%%20Compatibles%%20%%5BTOSEC%%5D%%2FIBM%%20PC%%20Compatibles%%20-%%20Operating%%20Systems%%20-%%20%%5BIMA%%5D%%20%%28TOSEC-v2011-01-06_CM%%29%%2FCaldera%%20DR-DOS%%20v7.03%%20%%281998%%29%%28Caldera%%20Systems%%29%%28Disk%%20%d%%20of%%205%%29.zip

IMGCNT=1
#IMGCNT=5

. ./include/pcdos_download+extract.sh

TMP_DIR=/tmp/drdos703-$USER

download_and_extract_pcdos "$1"
