#!/bin/sh

FREEDOS_BASE_URL=http://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.1/repos/base
FREEDOS_MAIN_FILES="command"
FREEDOS_TOOLS="kernel command assign attrib choice comp debug defrag deltree diskcomp diskcopy edit \
exe2bin fc find format help label mem mode more move nansi replace share shsucdx \
sort swsubst tree xcopy"

TMP_DIR=/tmp/freedos-$USER
DRIVE_ROOT="$1"
DOSEMU_EXECUTABLE=`which dosemu`
DOSEMU_SYSPREFIX=`dirname ${DOSEMU_EXECUTABLE}`/..
DOSEMU_DRIVEZ_DIR=`realpath ${DOSEMU_SYSPREFIX}`/share/dosemu/drive_z

. ./include/download.sh

extract_freedos_archives()
{
  for tool in ${FREEDOS_TOOLS}
  do
    unzip -d "$DRIVE_ROOT" -qq -LL "${TMP_DIR}"/"$tool".zip -x source/* bin/kernl86.sys 2>/dev/null
  done
}

download_archives()
{
  echo Downloading FreeDOS...
  mkdir -p "${TMP_DIR}"
  for filename in ${FREEDOS_MAIN_FILES} ${FREEDOS_TOOLS}
  do
    download_file "${FREEDOS_BASE_URL}"/"$filename".zip "${TMP_DIR}"/"$filename".zip
  done
  echo Downloading done
}

download_archives

echo Extracting FreeDOS...
mkdir -p "${DRIVE_ROOT}"
extract_freedos_archives

mv "${DRIVE_ROOT}"/bin/kernl386.sys "${DRIVE_ROOT}"/kernel.sys
ln -s bin/command.com "${DRIVE_ROOT}"/command.com

echo Extraction complete
