#!/bin/sh

if [ ! `which gocr` ] ; then
  echo Please install gocr and make sure that gocr is on your PATH
  exit 1
fi

if [ ! `which convert` ] ; then
  echo Please install ImageMagick and make sure that convert is on your PATH
  exit 1
fi

if [ ! `which xdotool` ] ; then
  echo Please install xdotool and make sure that xdotool is on your PATH
  exit 1
fi

set_window_id()
{
  while [ -z $WINDOW_ID ]; do
    WINDOW_ID=`xdotool search --name "$$"`
  done
}

# gocr has problems when there are different sizes/fonts on one shot so there are variants with crop to work around that
wait_for_text()
{
  while true; do
    TEXT=`xwd -silent -id $WINDOW_ID | convert - pnm:- |gocr -i -`
    if [ "${TEXT#*$1}" != "$TEXT" ]; then
      break;
    fi
    TEXT=`xwd -silent -id $WINDOW_ID | convert -crop 800x600+100+100 - pnm:- |gocr -i -`
    if [ "${TEXT#*$1}" != "$TEXT" ]; then
      break;
    fi
    TEXT=`xwd -silent -id $WINDOW_ID | convert -crop 640x480+0+0 - pnm:- |gocr -i -`
    if [ "${TEXT#*$1}" != "$TEXT" ]; then
      break;
    fi
  done
}

press_enter()
{
  xdotool key  --window $WINDOW_ID Return
}

press()
{
  xdotool key  --window $WINDOW_ID $@
}

type()
{
  xdotool type --window $WINDOW_ID $@
}

copy_if_exists()
{
  if [ -f "$1" ]; then
    cp "$1" "$2"
  fi
}

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 DIRECTORY" >&2
  echo "DIRECTORY should be empty or non-existant, then it will be created." >&2
  echo "Example: $0 /tmp/win31" >&2
  exit 1
fi

# dosemu doesn't check the environment variables when this file is not there, seems like a bug
if [ ! -e ${HOME}/.dosemurc ]; then
  touch ${HOME}/.dosemurc
fi

mkdir -p $1/c $1/d
echo \${DOSEMU_COMMANDS_DIR} > "$1"/e.lnk

./downloaddos -d msdos622 /tmp/dosinst/msdos622
./installdos /tmp/dosinst/msdos622/ $1/c

copy_if_exists /usr/local/share/dosemu/commands/config.sys "$1"/c
copy_if_exists /usr/local/share/dosemu/commands/autoexec.bat "$1"/c
copy_if_exists /usr/share/dosemu/commands/config.sys "$1"/c
copy_if_exists /usr/share/dosemu/commands/autoexec.bat "$1"/c
export dosemu__hdimage="$1/*"

./dostricks $1/c/inst/win31 win31
./win31drv $1/c/inst/win31drv

export dosemu__X_title="automated by $$"
dosemu &
set_window_id

wait_for_text 'C:\\'

type cd \\inst\\win31
press_enter
type setup
press_enter

wait_for_text Windows

press_enter
wait_for_text Custom
type c
wait_for_text directory
press_enter

# Computer
wait_for_text asterisk
press Up Up Up Up Up Up Up Return
wait_for_text type
press Down Down Down Down Down Down Down Down Down Down Down Down Down Down Down Return

# Display
wait_for_text asterisk
press Up Up Up Up Up Up Return
wait_for_text installed
press Down Down Down Down Down Down Down Down Down Down Down Down Down Down Down \
 Down Down Down Down Down Down Down Down Down Down Down Down Down Down Down Return
wait_for_text manufacturer
press Home
type \\inst\\win31drv\\video
press_enter
wait_for_text chosen
# 1024x768x8 small fonts
press Down Down Return
# 1024x768x8 large fonts
#press Down Down Down Return

# Mouse
wait_for_text asterisk
press Up Up Up Up Up Return
wait_for_text list
press Down Down Down Down Down Down Down Down Down Down Down Down Down Down Down Return
wait_for_text manufacturer
press Home
type \\inst\\win31drv\\mouse
press_enter
wait_for_text chosen
press_enter

wait_for_text asterisk
press_enter

# enter your full name
wait_for_text full
type User
press alt+o
#verify it's correct
wait_for_text verify
press alt+o

wait_for_text selected
press alt+o

# select components
wait_for_text groups
press alt+o

# Virtual Memory
wait_for_text temp
press space

# update connfig.sys and autoexec.bat
wait_for_text moditication
press alt+o

# confirm above
wait_for_text 'old version'
press space

# choose a printer
wait_for_text printer
press Tab Tab space

# search applications
wait_for_text Search
press alt+s
# set name for edit
wait_for_text name
press_enter

# add all applications
#wait_for_text hard
sleep 1
press alt+d Return

# Tutorial
wait_for_text been
press alt+s

# Reboot to finish
wait_for_text prompt
press alt+r

echo Run \'dosemu__hdimage="$1/*" dosemu\' to start DOSEMU2 with the installed system
