#!/bin/sh

DESTINATION=$1

IMG_BASE_URL=http://archive.org/download/IBM_PC_Compatibles_TOSEC_2012_04_23/IBM_PC_Compatibles_TOSEC_2012_04_23.zip

#MS-DOS 6.22
IMGURL=$IMG_BASE_URL/IBM%%20PC%%20Compatibles%%20%%5BTOSEC%%5D%%2FIBM%%20PC%%20Compatibles%%20-%%20Operating%%20Systems%%20-%%20%%5BIMA%%5D%%20%%28TOSEC-v2011-01-06_CM%%29%%2FMicrosoft%%20MS-DOS%%20v6.22%%20%%281994%%29%%28Microsoft%%29%%28Disk%%20%d%%20of%%203%%29.zip
IMGCNT=3

#IMGURL=$IMG_BASE_URL/IBM%%20PC%%20Compatibles%%20%%5BTOSEC%%5D%%2FIBM%%20PC%%20Compatibles%%20-%%20Operating%%20Systems%%20-%%20%%5BIMA%%5D%%20%%28TOSEC-v2011-01-06_CM%%29%%2FCaldera%%20DR-DOS%%20v7.03%%20%%281998%%29%%28Caldera%%20Systems%%29%%28Disk%%20%d%%20of%%205%%29.zip
#IMGCNT=5


TMP_DIR=/tmp/loaddosinst

. ./include/diskimage_download+extract.sh

mkdir -p "$DESTINATION"
download_and_extract "$IMGURL" "$IMGCNT" "$DESTINATION"
