#!/bin/sh
DESTINATION="$1"
TMP_DIR=/tmp/$0-$USER

. ./include/download.sh
. ./include/extract.sh

mkdir -p "$TMP_DIR" "$DESTINATION"/mouse "$DESTINATION"/video "$DESTINATION"/audio "$DESTINATION"/audio2
download_file https://github.com/stsp/win31-mouse-driver/blob/master/out/i33mouse.drv?raw=true "$DESTINATION"/mouse/i33mouse.drv
download_file https://raw.githubusercontent.com/stsp/win31-mouse-driver/master/out/oemsetup.inf "$DESTINATION"/mouse/oemsetup.inf

download_file http://files.mpoli.fi/hardware/DISPLAY/TRIDENT/TVGAW31A.ZIP "$TMP_DIR"/tvgaw31a.zip
download_file http://files.mpoli.fi/hardware/DISPLAY/TRIDENT/TVGAW31B.ZIP "$TMP_DIR"/tvgaw31b.zip

download_file https://github.com/jschwartzenberg/dos-download-scripts/blob/master/sb16w31/sb16.tar.xz?raw=true "$TMP_DIR"/sb16.tar.xz

download_file http://files2.europe.creative.com/manualdn/Drivers/Others/272/s16dw3up.exe "$TMP_DIR"/s16dw3up.exe

extract_7z "$TMP_DIR"/tvgaw31a.zip "" "$DESTINATION"/video/
extract_7z "$TMP_DIR"/tvgaw31b.zip "" "$DESTINATION"/video/

cp "$TMP_DIR"/sb16.tar.xz ""  "$DESTINATION"/audio/

extract_7z "$TMP_DIR"/s16dw3up.exe ""  "$DESTINATION"/audio2/
