#!/bin/sh
DESTINATION="$1"
TMP_DIR=/tmp/$0-$USER

. ./include/download.sh
. ./include/extract.sh

mkdir -p "$TMP_DIR" "$DESTINATION"/win3euro "$DESTINATION"/wing "$DESTINATION"/v4w "$DESTINATION"/ie5

# euro symbol
download_file https://web.archive.org/web/20010708140540/http://www.eu.microsoft.com/spain/support/kbsl/softlib/msfiles/win3euro.exe "$TMP_DIR"/win3euro.exe

# wing
download_file https://archive.org/download/ftp.microsoft.com/ftp.microsoft.com.zip/ftp.microsoft.com%2FSoftlib%2FMSLFILES%2FWING10.EXE "$TMP_DIR"/wing10.exe

# v4w
#download_file http://ftp.ulb.ac.be/pub/resulb/PC/Netscape/wv1160.exe "$TMP_DIR"/wv1160.exe
download_file http://ftp.lanet.lv/ftp/windows/www/netscape3.0/wv1160.exe "$TMP_DIR"/wv1160.exe

# ie5
# http://2ch-matome-smartphone.blog.jp/archives/1026316450.html
# http://web.archive.org/web/20040608163954/http://download.microsoft.com/msdownload/ie5/rtw/win16/en/cab/setup.exe
# http://web.archive.org/web/20030221021934/http://download.microsoft.com/msdownload/ie5/rtw/win16/en/cab/browser.cab
#download_file #https://web.archive.org/web/20020918054115/http://www.cintek.com/download/files/win31/ie5/ie5win31.exe "$TMP_DIR"/ie5win31.exe

extract_7z "$TMP_DIR"/wing10.exe "" "$DESTINATION"/wing
extract_7z "$TMP_DIR"/wv1160.exe "" "$DESTINATION"/v4w
extract_7z "$TMP_DIR"/win3euro.exe "" "$DESTINATION"/win3euro
# workaround for broken xdotool
ln -s "$DESTINATION"/win3euro/W31_EURO.BAT "$DESTINATION"/win3euro/W31-EURO.BAT
#extract_7z "$TMP_DIR"/ie5win31.exe "" "$DESTINATION"/ie5

# http://gaby.de/ftp/pub/win3x/archive/index.txt
# https://ia802603.us.archive.org/zipview.php?zip=/13/items/ftp.microsoft.com/ftp.microsoft.com.zip

#https://archive.org/download/ftp.microsoft.com/ftp.microsoft.com.zip/ftp.microsoft.com%2FSoftlib%2FMSLFILES%2FWIN31.EXE
#https://archive.org/download/ftp.microsoft.com/ftp.microsoft.com.zip/ftp.microsoft.com%2FSoftlib%2FMSLFILES%2FWIN31DSK.EXE
