#!/bin/sh
DESTINATION="$1"
TMP_DIR=/tmp/$0-$USER

. ./include/download.sh
. ./include/extract.sh

mkdir -p "$TMP_DIR" "$DESTINATION"/w31-euro "$DESTINATION"/wing "$DESTINATION"/v4w

# euro symbol
#download_file http://www.conradshome.com/win31/files/win3euro.exe "$TMP_DIR"/win3euro.exe

# wing
download_file https://archive.org/download/ftp.microsoft.com/ftp.microsoft.com.zip/ftp.microsoft.com%2FSoftlib%2FMSLFILES%2FWING10.EXE "$TMP_DIR"/wing10.exe

# v4w
download_file https://support.toshiba.ca/support/isg/drivers/archives/files_Archive/win3x/wv1160.exe "$TMP_DIR"/wv1160.exe


extract_7z "$TMP_DIR"/wing10.exe "" "$DESTINATION"/wing
extract_7z "$TMP_DIR"/wv1160.exe "" "$DESTINATION"/v4w

# ie5
# http://www.conradshome.com/win31/files/ie5ful16.zip
# http://browsers.evolt.org/archive/ie/win16/5.01/ie501.zip

# http://gaby.de/ftp/pub/win3x/archive/index.txt
# https://ia802603.us.archive.org/zipview.php?zip=/13/items/ftp.microsoft.com/ftp.microsoft.com.zip

#https://archive.org/download/ftp.microsoft.com/ftp.microsoft.com.zip/ftp.microsoft.com%2FSoftlib%2FMSLFILES%2FWIN31.EXE
#https://archive.org/download/ftp.microsoft.com/ftp.microsoft.com.zip/ftp.microsoft.com%2FSoftlib%2FMSLFILES%2FWIN31DSK.EXE